declare let startTime: number;
declare let maxTests: number;
declare const isTestPassed: {
    total: number;
    failed: number;
    passed: number;
};
declare const describe: function;
declare const test: function;
declare const incrementTests: () => number;
declare const incrementPassed: () => number;
declare const incrementFailed: () => number;
declare const assertions: (numberOfTests: number) => void;
declare const it: typeof test;
declare const startTest: () => number;
declare const endTest: () => void;
declare const expect: object;
declare const printFailed: (message: any) => void;
declare const printReturned: (value: any) => void;
declare const printPassed: (message: any) => void;
declare const checkIfLastTest: () => void;
declare const toBe: (value: any, toCompare: any, message: any) => void;
declare const toTypeEqual: (value: any, toCompare: any, message: any) => void;
declare const toStrictTypeEqual: (value: any, toCompare: any, message: string) => void;
declare const toEqual: (value: any, toCompare: any, message: string) => void;
declare const toStrictEqual: (value: any, toCompare: any, message: string) => void;
declare const toNotBe: (value: any, toCompare: any, message: string) => void;
declare const toTypeNotEqual: (value: any, toCompare: any, message: string) => void;
declare const toStrictTypeNotEqual: (value: any, toCompare: any, message: string) => void;
declare const toNotEqual: (value: any, toCompare: any, message: string) => void;
declare const toStrictNotEqual: (value: any, toCompare: any, message: string) => void;
